function on_game_start()
    RegisterScriptCallback("on_specific_character_dialog_list", function(character_id, dialog_list)
        if character_id == "jup_b220_trapper" then
            local res = dialog_list:add("dm_init_trader")
			
			-- test
            if res then
                printf("adding dialog %s for %s, pos %s", "dm_init_trader", character_id, res)
            end
        end
    end)
end